export { default as DashboardLayout } from "./DashboardLayout"
export { default as ProfileHome } from "./home/Home"
export { default as AddPost } from "./posts/addPost/AddPost"
// // export { default as EditPost } from "./posts/addPost/EditPost"
export { default as MyProfile } from "./profile/Profile"
// export { default as Settings } from "./settings/Settings"