export { default as SearchInput } from "./forms/SearchInput"
export { default as SelectInput } from "./forms/SelectInput"
export { default as TextAreaInput } from "./forms/teaxtAreaInput"
export { default as FormInput } from "./forms/FormInput"
export { default as SubmitBtn } from "./forms/SubmitBtn"
export { default as Loading } from "./forms/Loading"
export { default as ModalForDelete } from "./forms/ModalForDelete"
export { default as FileUpload } from "./forms/FileUpload/FileUpload"
export { default as TextEditor } from "./forms/TextEditor"
export { default as AutoInput } from "./forms/AutoInput"
export { default as CheckboxInput } from "./forms/CheckboxInput"
export { default as Pagination } from "./forms/Pagination"
export { default as FormArrayInput } from "./forms/FormArrayInput"

// export { default as LoadingLayout } from "./layouts/Loading"
